In [4]:
import pandas as pd
import numpy as np
import tensorflow as tf
import os
import json
from collections import Counter
from math import log

In [5]:
# 1. LOAD & PREPROCESSING DATA
def load_data():
    # Nanti Akan Load Data dari Database
    articles_df = pd.read_csv('articles.csv')
    likes_df = pd.read_csv('likes.csv')
    comments_df = pd.read_csv('comments.csv')
    return articles_df, likes_df, comments_df

In [6]:
def preprocess_data(articles_df, likes_df, comments_df):
    # Calculate likes per article
    article_likes = likes_df.groupby('article_id').size().reset_index(name='likes_count')
    
    # Calculate comments per article
    article_comments = comments_df.groupby('article_id').size().reset_index(name='comments_count')
    
    # Combine data with articles
    articles_enriched = articles_df.copy()
    articles_enriched['UUID'] = articles_enriched['UUID'].astype(str)
    
    # Add likes count
    articles_enriched = articles_enriched.merge(article_likes, left_on='UUID', right_on='article_id', how='left')
    articles_enriched['likes_count'] = articles_enriched['likes_count'].fillna(0)
    
    # Add comments count
    articles_enriched = articles_enriched.merge(article_comments, left_on='UUID', right_on='article_id', how='left')
    articles_enriched['comments_count'] = articles_enriched['comments_count'].fillna(0)
    
    # Clean up
    articles_enriched = articles_enriched.drop(['article_id_x', 'article_id_y'], axis=1, errors='ignore')
    
    # Extract features from article title using Text Processing
    # Combine title, province, and city for text-based features
    articles_enriched['text_features'] = articles_enriched['title'] + ' ' + articles_enriched['province'] + ' ' + articles_enriched['city']
    
    # Add engagement score
    articles_enriched['engagement_score'] = articles_enriched['likes_count'] + (2 * articles_enriched['comments_count'])
    
    return articles_enriched

In [7]:
class TFContentBasedRecommender:
    def __init__(self):
        self.vocab = {}
        self.idf = {}
        self.article_embeddings = None
        self.articles_df = None
        self.model = None
        self.model_path = 'models/tf_content_recommender'

    def _tokenize(self, text):
        return text.lower().split()

    def _build_vocab(self, texts):
        vocab_counter = Counter()
        for text in texts:
            tokens = self._tokenize(text)
            vocab_counter.update(tokens)
        self.vocab = {word: idx for idx, (word, _) in enumerate(vocab_counter.items())}
    
    def _compute_idf(self, texts):
        N = len(texts)
        df = Counter()
        for text in texts:
            tokens = set(self._tokenize(text))
            df.update(tokens)
        self.idf = {word: log(N / (df[word] + 1)) for word in self.vocab}

    def _tfidf_vector(self, text):
        tokens = self._tokenize(text)
        tf = Counter(tokens)
        vector = np.zeros(len(self.vocab))
        for token in tokens:
            if token in self.vocab:
                tf_val = tf[token] / len(tokens)
                idf_val = self.idf.get(token, 0)
                vector[self.vocab[token]] = tf_val * idf_val
        return vector

    def _build_model(self, input_dim):
        model = tf.keras.Sequential([
            tf.keras.layers.Dense(128, activation='relu', input_shape=(input_dim,)),
            tf.keras.layers.Dense(64, activation='relu')
        ])
        return model

    def fit(self, articles_df):
        self.articles_df = articles_df.copy()
        texts = self.articles_df['text_features'].tolist()

        self._build_vocab(texts)
        self._compute_idf(texts)

        tfidf_matrix = np.array([self._tfidf_vector(text) for text in texts])
        self.model = self._build_model(input_dim=tfidf_matrix.shape[1])
        self.article_embeddings = self.model.predict(tfidf_matrix)

        return self

    def recommend(self, article_id, top_n=5):
        idx = self.articles_df[self.articles_df['UUID'] == article_id].index[0]
        query_embedding = self.article_embeddings[idx].reshape(1, -1)

        similarity = np.dot(self.article_embeddings, query_embedding.T).flatten()
        norms = np.linalg.norm(self.article_embeddings, axis=1) * np.linalg.norm(query_embedding)
        similarity = similarity / norms

        sim_indices = np.argsort(similarity)[::-1][1:top_n+1]
        recommended_articles = self.articles_df.iloc[sim_indices][['UUID', 'title', 'province', 'city']].copy()
        recommended_articles['similarity_score'] = similarity[sim_indices]

        return recommended_articles

    def save_model(self):
        os.makedirs(self.model_path, exist_ok=True)
        np.save(os.path.join(self.model_path, 'article_embeddings.npy'), self.article_embeddings)
        self.articles_df.to_pickle(os.path.join(self.model_path, 'articles_df.pkl'))

        with open(os.path.join(self.model_path, 'vocab.json'), 'w') as f:
            json.dump(self.vocab, f)
        with open(os.path.join(self.model_path, 'idf.json'), 'w') as f:
            json.dump(self.idf, f)

    def load_model(self):
        if os.path.exists(self.model_path):
            self.article_embeddings = np.load(os.path.join(self.model_path, 'article_embeddings.npy'))
            self.articles_df = pd.read_pickle(os.path.join(self.model_path, 'articles_df.pkl'))

            with open(os.path.join(self.model_path, 'vocab.json'), 'r') as f:
                self.vocab = json.load(f)
            with open(os.path.join(self.model_path, 'idf.json'), 'r') as f:
                self.idf = json.load(f)

            return True
        return False

    def update_model(self, new_articles_df):
        if self.articles_df is not None:
            existing_uuids = set(self.articles_df['UUID'].values)
            new_articles = new_articles_df[~new_articles_df['UUID'].isin(existing_uuids)]

            if len(new_articles) > 0:
                self.articles_df = pd.concat([self.articles_df, new_articles]).reset_index(drop=True)
                self.fit(self.articles_df)
                self.save_model()
                return True, f"Model updated with {len(new_articles)} new articles"
            return False, "No new articles to update"
        else:
            self.fit(new_articles_df)
            self.save_model()
            return True, f"Initial model created with {len(new_articles_df)} articles"

In [8]:
# Memuat data
articles_df, likes_df, comments_df = load_data()

In [9]:
articles_df

,ID,UUID,title,slug,province,city,active,User_ID
0,1,a1b2c3d4-1111,Wisata Pantai Kuta,wisata-pantai-kuta,Bali,Denpasar,True,u1e2f3g4-1111
1,2,a1b2c3d4-2222,Kuliner Gudeg Jogja,kuliner-gudeg-jogja,DI Yogyakarta,Yogyakarta,True,u1e2f3g4-2222
2,3,a1b2c3d4-3333,Mendaki Gunung Bromo,mendaki-gunung-bromo,Jawa Timur,Probolinggo,True,u1e2f3g4-1111
3,4,a1b2c3d4-4444,Sejarah Candi Borobudur,sejarah-candi-borobudur,Jawa Tengah,Magelang,True,u1e2f3g4-3333
4,5,a1b2c3d4-5555,Tips Belanja di Malioboro,tips-belanja-malioboro,DI Yogyakarta,Yogyakarta,True,u1e2f3g4-2222
5,6,a1b2c3d4-6666,Mengenal Tari Kecak,mengenal-tari-kecak,Bali,Denpasar,True,u1e2f3g4-4444
6,7,a1b2c3d4-7777,Keindahan Raja Ampat,keindahan-raja-ampat,Papua Barat,Raja Ampat,True,u1e2f3g4-3333
7,8,a1b2c3d4-8888,Menjelajah Kawah Ijen,menjelajah-kawah-ijen,Jawa Timur,Banyuwangi,True,u1e2f3g4-1111
8,9,a1b2c3d4-9999,Festival Cap Go Meh,festival-cap-go-meh,Kalimantan Barat,Singkawang,True,u1e2f3g4-5555
9,10,a1b2c3d4-0000,Tradisi Ngaben di Bali,tradisi-ngaben-bali,Bali,Denpasar,True,u1e2f3g4-4444

In [10]:
likes_df

    ID           UUID        user_id     article_id
0    1  l1m2n3o4-1111  u1e2f3g4-3333  a1b2c3d4-1111
1    2  l1m2n3o4-2222  u1e2f3g4-5555  a1b2c3d4-1111
2    3  l1m2n3o4-3333  u1e2f3g4-2222  a1b2c3d4-1111
3    4  l1m2n3o4-4444  u1e2f3g4-1111  a1b2c3d4-2222
4    5  l1m2n3o4-5555  u1e2f3g4-3333  a1b2c3d4-2222
5    6  l1m2n3o4-6666  u1e2f3g4-4444  a1b2c3d4-3333
6    7  l1m2n3o4-7777  u1e2f3g4-5555  a1b2c3d4-3333
7    8  l1m2n3o4-8888  u1e2f3g4-2222  a1b2c3d4-3333
8    9  l1m2n3o4-9999  u1e2f3g4-1111  a1b2c3d4-3333
9   10  l1m2n3o4-0001  u1e2f3g4-4444  a1b2c3d4-4444
10  11  l1m2n3o4-0002  u1e2f3g4-3333  a1b2c3d4-5555
11  12  l1m2n3o4-0003  u1e2f3g4-1111  a1b2c3d4-5555
12  13  l1m2n3o4-0004  u1e2f3g4-5555  a1b2c3d4-6666
13  14  l1m2n3o4-0005  u1e2f3g4-2222  a1b2c3d4-7777
14  15  l1m2n3o4-0006  u1e2f3g4-3333  a1b2c3d4-7777
15  16  l1m2n3o4-0007  u1e2f3g4-4444  a1b2c3d4-8888
16  17  l1m2n3o4-0008  u1e2f3g4-1111  a1b2c3d4-8888
17  18  l1m2n3o4-0009  u1e2f3g4-2222  a1b2c3d4-9999
18  19  l1m2n3o4-0010  u1e2f3g4-4444  a1b2c3d4-9999
19  20  l1m2n3o4-0011  u1e2f3g4-3333  a1b2c3d4-0000

In [11]:
comments_df

    ID           UUID     article_id        user_id
0    1  c1d2e3f4-1111  a1b2c3d4-1111  u1e2f3g4-3333
1    2  c1d2e3f4-2222  a1b2c3d4-1111  u1e2f3g4-5555
2    3  c1d2e3f4-3333  a1b2c3d4-1111  u1e2f3g4-2222
3    4  c1d2e3f4-4444  a1b2c3d4-1111  u1e2f3g4-1111
4    5  c1d2e3f4-5555  a1b2c3d4-2222  u1e2f3g4-1111
5    6  c1d2e3f4-6666  a1b2c3d4-2222  u1e2f3g4-3333
6    7  c1d2e3f4-7777  a1b2c3d4-2222  u1e2f3g4-2222
7    8  c1d2e3f4-8888  a1b2c3d4-3333  u1e2f3g4-4444
8    9  c1d2e3f4-9999  a1b2c3d4-3333  u1e2f3g4-5555
9   10  c1d2e3f4-0001  a1b2c3d4-3333  u1e2f3g4-1111
10  11  c1d2e3f4-0002  a1b2c3d4-4444  u1e2f3g4-4444
11  12  c1d2e3f4-0003  a1b2c3d4-5555  u1e2f3g4-3333
12  13  c1d2e3f4-0004  a1b2c3d4-5555  u1e2f3g4-1111
13  14  c1d2e3f4-0005  a1b2c3d4-5555  u1e2f3g4-2222
14  15  c1d2e3f4-0006  a1b2c3d4-6666  u1e2f3g4-5555
15  16  c1d2e3f4-0007  a1b2c3d4-7777  u1e2f3g4-2222
16  17  c1d2e3f4-0008  a1b2c3d4-8888  u1e2f3g4-4444
17  18  c1d2e3f4-0009  a1b2c3d4-9999  u1e2f3g4-2222
18  19  c1d2e3f4-0010  a1b2c3d4-0000  u1e2f3g4-3333
19  20  c1d2e3f4-0011  a1b2c3d4-0000  u1e2f3g4-5555

In [12]:
# Proses data
articles_enriched = preprocess_data(articles_df, likes_df, comments_df)

In [13]:
articles_enriched

,ID,UUID,title,slug,province,city,active,User_ID,likes_count,comments_count,text_features,engagement_score
0,1,a1b2c3d4-1111,Wisata Pantai Kuta,wisata-pantai-kuta,Bali,Denpasar,True,u1e2f3g4-1111,3,4,Wisata Pantai Kuta Bali Denpasar,11
1,2,a1b2c3d4-2222,Kuliner Gudeg Jogja,kuliner-gudeg-jogja,DI Yogyakarta,Yogyakarta,True,u1e2f3g4-2222,2,3,Kuliner Gudeg Jogja DI Yogyakarta Yogyakarta,8
2,3,a1b2c3d4-3333,Mendaki Gunung Bromo,mendaki-gunung-bromo,Jawa Timur,Probolinggo,True,u1e2f3g4-1111,4,3,Mendaki Gunung Bromo Jawa Timur Probolinggo,10
3,4,a1b2c3d4-4444,Sejarah Candi Borobudur,sejarah-candi-borobudur,Jawa Tengah,Magelang,True,u1e2f3g4-3333,1,1,Sejarah Candi Borobudur Jawa Tengah Magelang,3
4,5,a1b2c3d4-5555,Tips Belanja di Malioboro,tips-belanja-malioboro,DI Yogyakarta,Yogyakarta,True,u1e2f3g4-2222,2,3,Tips Belanja di Malioboro DI Yogyakarta Yogyak...,8
5,6,a1b2c3d4-6666,Mengenal Tari Kecak,mengenal-tari-kecak,Bali,Denpasar,True,u1e2f3g4-4444,1,1,Mengenal Tari Kecak Bali Denpasar,3
6,7,a1b2c3d4-7777,Keindahan Raja Ampat,keindahan-raja-ampat,Papua Barat,Raja Ampat,True,u1e2f3g4-3333,2,1,Keindahan Raja Ampat Papua Barat Raja Ampat,4
7,8,a1b2c3d4-8888,Menjelajah Kawah Ijen,menjelajah-kawah-ijen,Jawa Timur,Banyuwangi,True,u1e2f3g4-1111,2,1,Menjelajah Kawah Ijen Jawa Timur Banyuwangi,4
8,9,a1b2c3d4-9999,Festival Cap Go Meh,festival-cap-go-meh,Kalimantan Barat,Singkawang,True,u1e2f3g4-5555,2,1,Festival Cap Go Meh Kalimantan Barat Singkawang,4
9,10,a1b2c3d4-0000,Tradisi Ngaben di Bali,tradisi-ngaben-bali,Bali,Denpasar,True,u1e2f3g4-4444,1,2,Tradisi Ngaben di Bali Bali Denpasar,5

In [14]:
# Inisialisasi model Content-Based Recommender
recommender = TFContentBasedRecommender()
recommender.fit(articles_enriched)

d:\dicoding\capstone\venv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 115ms/step

In [15]:
# Mendapatkan rekomendasi
article_id = 'a1b2c3d4-1111'  # ID artikel referensi
recommendations = recommender.recommend(article_id, top_n=3)
    
print(f"Rekomendasi untuk artikel '{articles_df[articles_df['UUID'] == article_id]['title'].values[0]}':")
for _, row in recommendations.iterrows():
    print(f"- {row['title']} (Skor: {row['similarity_score']:.4f})")

Rekomendasi untuk artikel 'Wisata Pantai Kuta':
- Keindahan Raja Ampat (Skor: 0.6077)
- Festival Cap Go Meh (Skor: 0.5725)
- Menjelajah Kawah Ijen (Skor: 0.5529)

In [20]:
# Memberikan rekomendasi artikel berdasarkan artikel dengan UUID tertentu
article_id = 'a1b2c3d4-1111'
recommended_articles = recommender.recommend(article_id=article_id, top_n=5)
print("Artikel yang direkomendasikan:")
recommended_articles

Artikel yang direkomendasikan:

,UUID,title,province,city,similarity_score
6,a1b2c3d4-7777,Keindahan Raja Ampat,Papua Barat,Raja Ampat,0.607661
8,a1b2c3d4-9999,Festival Cap Go Meh,Kalimantan Barat,Singkawang,0.572514
7,a1b2c3d4-8888,Menjelajah Kawah Ijen,Jawa Timur,Banyuwangi,0.552893
3,a1b2c3d4-4444,Sejarah Candi Borobudur,Jawa Tengah,Magelang,0.508172
4,a1b2c3d4-5555,Tips Belanja di Malioboro,DI Yogyakarta,Yogyakarta,0.481145

In [21]:
# Menyimpan model
recommender.save_model()